# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Data Exfiltration Detection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.3
      uses: actions/setup-python@v2
      with:
        python-version: "3.7.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Reformat with black
      run: |
        black .
    - name: Lint with PyLint
      run: |
        pylint tests/**/*.py
        pylint tests/data-eng/**/*.py
    - name: Test with pytest
      run: |
        pytest
